In [0]:
from collections import OrderedDict
import pandas as pd
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.nn.functional as F

## Data

In [0]:
data = pd.read_csv('examen.csv', header=None)
y = data.iloc[:, 0].values
X = data.iloc[:, 1:].values

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train = (X_train) / X_train.max(axis=0)
X_test = (X_test) / X_train.max(axis=0)

X_train = torch.Tensor(X_train)
X_test = torch.Tensor(X_test)

y_train = torch.Tensor(y_train).reshape(-1, 1)
y_test = torch.Tensor(y_test).reshape(-1, 1)

## Proposed architecture
Built in Pytorch, the proposed architecture is 2 hidden layers, each with 5 neural units and Sigmoid activation

In [8]:
exam = nn.Sequential(
    nn.Linear(4, 5),
    nn.Sigmoid(),
    nn.Linear(5, 5),
    nn.Sigmoid(),
    nn.Linear(5, 5),
    nn.Sigmoid(),
    nn.Linear(5, 1)
)

exam

Sequential(
  (0): Linear(in_features=4, out_features=5, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=5, out_features=5, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=5, out_features=5, bias=True)
  (5): Sigmoid()
  (6): Linear(in_features=5, out_features=1, bias=True)
)

In [12]:
for i in exam:
  print(i)
  print(i._parameters)

Linear(in_features=4, out_features=5, bias=True)
OrderedDict([('weight', Parameter containing:
tensor([[-0.1337,  0.0874, -0.1069, -0.2706],
        [ 0.1733,  0.3348,  0.2583,  0.1232],
        [-0.0607, -0.1557, -0.3172,  0.3525],
        [-0.2465,  0.3329, -0.0024,  0.2357],
        [ 0.4099,  0.1306, -0.1127, -0.0377]], requires_grad=True)), ('bias', Parameter containing:
tensor([-0.4700,  0.2583, -0.1138,  0.2368, -0.2142], requires_grad=True))])
Sigmoid()
OrderedDict()
Linear(in_features=5, out_features=5, bias=True)
OrderedDict([('weight', Parameter containing:
tensor([[ 0.2459,  0.4003, -0.2752,  0.0781, -0.4327],
        [-0.2687, -0.1221, -0.0464, -0.2257, -0.2737],
        [ 0.2551, -0.1137,  0.0599, -0.1505,  0.2294],
        [-0.3911, -0.2979, -0.0358, -0.4079, -0.1854],
        [-0.1694, -0.2072, -0.3281, -0.3312,  0.3809]], requires_grad=True)), ('bias', Parameter containing:
tensor([-0.2059, -0.4174, -0.1822, -0.1115,  0.3775], requires_grad=True))])
Sigmoid()
OrderedDi

In [13]:
criterion = torch.nn.MSELoss() # Regression loss
optimizer = torch.optim.SGD(exam.parameters(), lr=3e-4) # Gradient descent optimizer

# Batches = 50
for e in range(50):
  y_pred = exam(X_train)
  loss = criterion(y_pred, y_train)
  print(f'{e}: mse = {loss.item()}')  
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

0: mse = 1.128915548324585
1: mse = 1.1281629800796509
2: mse = 1.1274125576019287
3: mse = 1.126664638519287
4: mse = 1.1259182691574097
5: mse = 1.125173807144165
6: mse = 1.1244314908981323
7: mse = 1.1236910820007324
8: mse = 1.1229528188705444
9: mse = 1.1222162246704102
10: mse = 1.1214816570281982
11: mse = 1.1207488775253296
12: mse = 1.1200183629989624
13: mse = 1.1192896366119385
14: mse = 1.118562936782837
15: mse = 1.1178377866744995
16: mse = 1.1171150207519531
17: mse = 1.116393804550171
18: mse = 1.1156747341156006
19: mse = 1.114957571029663
20: mse = 1.1142420768737793
21: mse = 1.1135286092758179
22: mse = 1.1128170490264893
23: mse = 1.1121076345443726
24: mse = 1.111399531364441
25: mse = 1.1106936931610107
26: mse = 1.1099895238876343
27: mse = 1.1092873811721802
28: mse = 1.1085870265960693
29: mse = 1.1078885793685913
30: mse = 1.1071919202804565
31: mse = 1.1064969301223755
32: mse = 1.1058039665222168
33: mse = 1.1051126718521118
34: mse = 1.1044236421585083
35

In [14]:
output = exam(X_train)
output.mean(), output.std()

(tensor(0.5410, grad_fn=<MeanBackward0>),
 tensor(0.0004, grad_fn=<StdBackward0>))

In [15]:
output

tensor([[0.5415],
        [0.5408],
        [0.5417],
        [0.5408],
        [0.5419],
        [0.5408],
        [0.5408],
        [0.5408],
        [0.5415],
        [0.5411],
        [0.5416],
        [0.5407],
        [0.5420],
        [0.5420],
        [0.5418],
        [0.5409],
        [0.5409],
        [0.5416],
        [0.5409],
        [0.5409],
        [0.5418],
        [0.5409],
        [0.5408],
        [0.5407],
        [0.5408],
        [0.5408],
        [0.5408],
        [0.5410],
        [0.5407],
        [0.5408],
        [0.5408],
        [0.5408],
        [0.5412],
        [0.5408],
        [0.5408],
        [0.5407],
        [0.5420],
        [0.5408],
        [0.5412],
        [0.5413],
        [0.5417],
        [0.5408],
        [0.5408],
        [0.5409],
        [0.5411],
        [0.5407],
        [0.5418],
        [0.5408],
        [0.5409],
        [0.5407],
        [0.5415],
        [0.5407],
        [0.5414],
        [0.5407],
        [0.5407],
        [0

In [0]:
win = nn.Sequential(
    nn.Linear(4, 10),
    nn.ReLU(),
    nn.Linear(10, 15),
    nn.ReLU(),
    nn.Linear(15, 1)
)

win

Sequential(
  (0): Linear(in_features=4, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=15, bias=True)
  (3): ReLU()
  (4): Linear(in_features=15, out_features=1, bias=True)
)

In [0]:
for i in win:
  print(i)
  print(i._parameters)

Linear(in_features=4, out_features=10, bias=True)
OrderedDict([('weight', Parameter containing:
tensor([[ 0.0155, -0.3776,  0.3114,  0.4694],
        [ 0.0716,  0.1584,  0.3808, -0.3638],
        [ 0.1397,  0.4312, -0.4030, -0.0305],
        [-0.4262,  0.4644, -0.1379, -0.3012],
        [ 0.0850, -0.3285,  0.4471, -0.1191],
        [-0.0354,  0.1519,  0.2079, -0.0301],
        [-0.2310, -0.3626, -0.4459,  0.0530],
        [-0.1818, -0.4020, -0.0613, -0.0583],
        [-0.4702,  0.1937,  0.2769,  0.3810],
        [-0.3232,  0.4275,  0.2161,  0.0170]], requires_grad=True)), ('bias', Parameter containing:
tensor([ 0.1458,  0.2591,  0.4638,  0.4248, -0.0126,  0.3330,  0.4252, -0.2919,
        -0.3201,  0.0661], requires_grad=True))])
ReLU()
OrderedDict()
Linear(in_features=10, out_features=15, bias=True)
OrderedDict([('weight', Parameter containing:
tensor([[ 0.2996, -0.2288,  0.2597, -0.2372, -0.2850, -0.1326,  0.2764, -0.1168,
          0.2439,  0.2335],
        [-0.2055, -0.1062, -0.049

In [0]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(win.parameters(), lr=3e-2)

for e in range(20):
  y_pred = win(X_train)
  loss = criterion(y_pred, y_train)
  print(f'{e}: mse = {loss.item()}')  
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

0: mse = 1.9537129402160645
1: mse = 1.6991448402404785
2: mse = 1.4643824100494385
3: mse = 1.2462984323501587
4: mse = 1.0439003705978394
5: mse = 0.857891857624054
6: mse = 0.690378725528717
7: mse = 0.5441642999649048
8: mse = 0.4203311502933502
9: mse = 0.3195432722568512
10: mse = 0.24098140001296997
11: mse = 0.18238769471645355
12: mse = 0.14038096368312836
13: mse = 0.11120956391096115
14: mse = 0.09133968502283096
15: mse = 0.07776576280593872
16: mse = 0.06825064867734909
17: mse = 0.06127804145216942
18: mse = 0.05589767545461655
19: mse = 0.05154058709740639


In [0]:
output = win(X_train)
output.mean(), output.std()

(tensor(1.0836, grad_fn=<MeanBackward0>),
 tensor(0.7384, grad_fn=<StdBackward0>))