# K-means clustering
_María Camila Vásquez Correa_

### Necessary packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from scipy.spatial.distance import cdist
%matplotlib inline

## Data loading
We will load the data, the higher dimensional data and the embbeding

In [2]:
n1 = 150  # Number of samples
N1 = 4    # Number of features
i1 = load_iris().data.T
# Normalization
for i in range(N1):
    i1[i] = i1[i]/np.max(i1[i])
i1 = i1.T
ie = pd.read_csv('iris_embbeding.csv').values
i2 = pd.read_csv('high_dimension_iris.csv').values

In [3]:
n2 = 284807  # Number of samples
N2 = 29    # Number of features
c1 = pd.read_csv('creditcard.csv')
c1.drop('Time', axis=1)
c1.drop('Class', axis = 1)
c1 = c1.values.T
# Normalization
for i in range(N2):
    c1[i] = c1[i]/np.max(c1[i])
c1 = c1.T
ce = pd.read_csv('credit_embbeding.csv').values
c2 = pd.read_csv('credit_pca.csv').values

### Parameters

In [4]:
# Data
X = i1
Y = ie
N = N1
n = n1

In [23]:
k = 7
epsilon = 0.005
n_iter = 10000
metric = 'euclidean'

In [15]:
def cost_function(clusters, data, metric):
    A = data.reshape((*data.shape,1))
    B = clusters.reshape((1,*clusters.shape))
    J = cdist(clusters, data, metric=metric) 
    J = np.sum(np.min(J, axis=-1))
    return J

In [16]:
# Compute the matrix U
def compute_U(clusters, data, metric):
    U = cdist(clusters, data, metric=metric).T 
    U = np.argmin(U, axis=-1)    
    return U

In [17]:
def update_cluster(U, data, k):
    c = np.arange(k).reshape(k,1)
    mask = U == c
    mask = np.expand_dims(mask, axis=-1)
    A = np.expand_dims(data, axis=0)
    mask = np.where(mask, A, np.nan)
    new_cluster = np.nanmean(mask, axis=1)
    return new_cluster

In [18]:
X.shape

(150, 4)

In [24]:
# Initialize the centers
c_random = np.random.randint(0,n,k)
clusters = X[c_random]
cluster_index = c_random

In [25]:
# Ciclo principal
Jdiff = np.inf
Jprev = np.inf
i = 0
while (Jdiff > epsilon) & (i < n_iter):
    # computar la matrix U
    U = compute_U(clusters, X, metric)
    # computar el costo
    J = cost_function(clusters, X, metric)
    # actualizar los clusters
    clusters = update_cluster(U, X, 3)
    Jdiff = np.abs(J-Jprev)
    Jprev = J
    i += 1

In [26]:
clusters

array([[0.82349795, 0.67797695, 0.76587059, 0.74816901],
       [0.63367089, 0.77909091, 0.21188406, 0.0984    ],
       [0.71715408, 0.59090909, 0.57671164, 0.48      ]])

In [27]:
plt.scatter(Y[:, 0], Y[:, 1], c=U, cmap = 'inferno')
plt.show()

In [31]:
import gc
random_seed = 12
rng = np.random.RandomState(random_seed)  # random_seed
rng.randint(0,150,3)

array([ 75, 134, 130])

In [38]:
def kmeans(X,k,metric):
    #n_iter = 10000
    gc.enable()
    N, n = X.shape
    # Initialize the centers
    c_random = rng.randint(0,n,k)
    clusters = X[c_random]
    cluster_index = c_random
    # Ciclo principal
    Jdiff = np.inf
    Jprev = np.inf
    i = 0
    while (Jdiff > epsilon): #& (i < n_iter):
        # computar la matrix U
        U = compute_U(clusters, X, metric)
        # computar el costo
        J = cost_function(clusters, X, metric)
        # actualizar los clusters
        clusters = update_cluster(U, X, k)
        Jdiff = np.abs(J-Jprev)
        Jprev = J
        i += 1
    return clusters

In [67]:
kmeans(i1,2,'cityblock')

array([[0.79265823, 0.65272727, 0.71101449, 0.6704    ],
       [0.63367089, 0.77909091, 0.21188406, 0.0984    ]])

In [79]:
kmeans(i1,3,'cityblock')

<ipython-input-17-ecbd5faad018>:7: RuntimeWarning: Mean of empty slice
  new_cluster = np.nanmean(mask, axis=1)


array([[       nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [0.73966245, 0.69484848, 0.54463768, 0.47973333]])

In [92]:
kmeans(i1,5,'cityblock')

<ipython-input-17-ecbd5faad018>:7: RuntimeWarning: Mean of empty slice
  new_cluster = np.nanmean(mask, axis=1)


array([[       nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [0.73966245, 0.69484848, 0.54463768, 0.47973333],
       [       nan,        nan,        nan,        nan]])